"""добавлена модель

Revision ID: 87cb50702e08
Revises: 58accba8b443
Create Date: 2025-02-04 14:09:34.168467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cb50702e08'
down_revision = '58accba8b443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignment', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
